theme: ElOtroMano/chirpy-blog-theme
#remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
#theme: minima
title: From Pins To Keys
author: ElOtroMano
description: Starting my contributions to cybersecurity after 15+ years as a community acupuncturist
