#remote_theme: cotes2020/jekyll-theme-chirpy
#remote_theme: pages-themes/time-machine@v0.2.0
#remote_theme: pages-themes/merlot@v0.2.0
#plugins:
#- jekyll-remote-theme
theme: minima
title: From Pins To Keys
author: ElOtroMano
description: Starting my contributions to cybersecurity after my time as a community acupuncturist
